AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 180
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
